services:
  multas-web:
    image: shemaop4/multas-web:1.0.1
    container_name: multas-web
    pull_policy: never

    ports:
      - "8080:80"

    restart: unless-stopped

    healthcheck:
      test:
        ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
